apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akkoma
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: akkoma
    repoURL: ghcr.io/adamancini/charts
    targetRevision: "0.4.2"
    helm:
      releaseName: akkoma
    #   values: |
    #     ingress:
    #       enabled: true
    #       hosts:
    #         - akkoma.{{name}}.kargo.akuity.io
  destination:
    namespace: akkoma
    server: "https://kubernetes.default.svc"
