apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: akkoma
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - stage: dev
            cluster_domain: dev.annarchy.net
            default_storage_class: local-path
          - stage: staging
            cluster_domain: staging.annarchy.net
            default_storage_class: local-path
          - stage: prod
            cluster_domain: annarchy.net
            default_storage_class: longhorn
  template:
    metadata:
      name: "akkoma-{{stage}}"
      namespace: argocd
      annotations:
        kargo.akuity.io/authorized-stage: "akkoma:{{stage}}"
    spec:
      project: default
      source:
        repoURL: ghcr.io/adamancini/charts
        chart: akkoma
        targetRevision: "*"
        helm:
          valuesObject:
            ingress:
              enabled: true
              className: traefik
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
              tls:
                enabled: true
                secretName: akkoma-tls
            resources:
              requests:
                cpu: 25m
                memory: 384Mi
              limits:
                memory: 768Mi
            akkoma:
              domain: "akkoma.{{cluster_domain}}"
              adminEmail: root@annarchy.net
            postgresql:
              resources:
                requests:
                  cpu: 25m
                  memory: 96Mi
                limits:
                  memory: 256Mi
              storageClass: "{{default_storage_class}}"
            storage:
              uploads:
                storageClass: "{{default_storage_class}}"
              frontends:
                storageClass: "{{default_storage_class}}"
            metrics:
              enabled: true
              serviceMonitor:
                enabled: false
              grafana:
                enabled: false
            mediaPruning:
              enabled: true
            networkPolicy:
              enabled: true
              ingressControllerLabels:
                kubernetes.io/metadata.name: traefik
      destination:
        name: kargo-quickstart
        namespace: "akkoma-{{stage}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
