apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: akkoma
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: akkoma-charts
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/adamancini/kargo-quickstart
      steps:
        - uses: argocd-update
          config:
            apps:
              - name: akkoma-${{ ctx.stage }}
                namespace: argocd
                sources:
                  - repoURL: "ghcr.io/adamancini/charts"
                    chart: akkoma
                    desiredRevision: ${{ chartFrom("oci://ghcr.io/adamancini/charts/akkoma").Version }}
              - name: soju-${{ ctx.stage }}
                namespace: argocd
                sources:
                  - repoURL: "ghcr.io/adamancini/charts"
                    chart: soju
                    desiredRevision: ${{ chartFrom("oci://ghcr.io/adamancini/charts/soju").Version }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: akkoma
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: akkoma-charts
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/adamancini/kargo-quickstart
      steps:
        - uses: argocd-update
          config:
            apps:
              - name: akkoma-${{ ctx.stage }}
                namespace: argocd
                sources:
                  - repoURL: "ghcr.io/adamancini/charts"
                    chart: akkoma
                    desiredRevision: ${{ chartFrom("oci://ghcr.io/adamancini/charts/akkoma").Version }}
              - name: soju-${{ ctx.stage }}
                namespace: argocd
                sources:
                  - repoURL: "ghcr.io/adamancini/charts"
                    chart: soju
                    desiredRevision: ${{ chartFrom("oci://ghcr.io/adamancini/charts/soju").Version }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: akkoma
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: akkoma-charts
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/adamancini/kargo-quickstart
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/akuity/akkoma-appset.yaml
            updates:
              - key: spec.template.spec.source.targetRevision
                value: ${{ chartFrom("oci://ghcr.io/adamancini/charts/akkoma").Version }}
        - uses: yaml-update
          config:
            path: ./repo/akuity/soju-appset.yaml
            updates:
              - key: spec.template.spec.source.targetRevision
                value: ${{ chartFrom("oci://ghcr.io/adamancini/charts/soju").Version }}
        - uses: git-commit
          config:
            path: ./repo
            message: >-
              chore: update AppSet bootstrap versions
              akkoma=${{ chartFrom("oci://ghcr.io/adamancini/charts/akkoma").Version }}
              soju=${{ chartFrom("oci://ghcr.io/adamancini/charts/soju").Version }}
        - uses: git-push
          config:
            path: ./repo
            targetBranch: main
        - uses: argocd-update
          config:
            apps:
              - name: akkoma-${{ ctx.stage }}
                namespace: argocd
                sources:
                  - repoURL: "ghcr.io/adamancini/charts"
                    chart: akkoma
                    desiredRevision: ${{ chartFrom("oci://ghcr.io/adamancini/charts/akkoma").Version }}
              - name: soju-${{ ctx.stage }}
                namespace: argocd
                sources:
                  - repoURL: "ghcr.io/adamancini/charts"
                    chart: soju
                    desiredRevision: ${{ chartFrom("oci://ghcr.io/adamancini/charts/soju").Version }}
