apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: soju
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: soju
  namespace: soju
spec:
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: true
    - stage: staging
      autoPromotionEnabled: false
    - stage: prod
      autoPromotionEnabled: false
