apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: soju-charts
  namespace: soju
spec:
  subscriptions:
    - chart:
        repoURL: oci://ghcr.io/adamancini/charts/soju
        constraint: ">=0.0.0-0"
